# Generated by Django 2.1.1 on 2018-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=128, unique=True, verbose_name='Keyword')),
            ],
            options={
                'ordering': ('key_word',),
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=128, verbose_name='Video ID')),
            ],
            options={
                'ordering': ('video_id',),
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='videos',
            field=models.ManyToManyField(related_name='keyboards', to='app.YoutubeVideo', verbose_name='Youtube video'),
        ),
    ]
